export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const UPDATE_CUSTOMER = "REMOVE_CUSTOMER";

export  const SET_ALERT = 'SET_ALERT'
export  const REMOVE_ALERT = 'REMOVE_ALERT'
export  const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export  const REGISTER_FAIL = 'REGISTER_FAIL'
export  const USER_LOADED = 'USER_LOADED'
export  const AUTH_ERROR = 'AUTH_ERROR'
export  const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export  const LOGIN_FAIL = 'LOGIN_FAIL'
export  const LOGOUT = 'LOGOUT'
export  const GET_PROFILE = 'GET_PROFILE'
export  const GET_PROFILES = 'GET_PROFILES'
export  const CLEAR_PROFILE = 'CLEAR_PROFILE'
export  const PROFILE_ERRORS = 'PROFILE_ERRORS'
export  const UPDATE_PROFILE = 'UPDATE_PROFILE'

export const TRANSATION_INITIALIZE = "TRANSATION_INITIALIZE"
export const TRANSACTION_SUCCESS = 'TRANSACTION_SUCCESS'
export const TRANSACTION_FAIL = 'TRANSACTION_FAIL'

export const ADD_CONTACT =  'ADD_CONTACT'
export const GET_CONTACTS = 'GET_CONTACTS'
export const CONTACT_ERROR = 'CONTACT_ERROR'
